### ISSUE TITLE
Run nixos-install against a proper subdir

### ISSUE THREAD

**Issue by wmertens** [elitak/nixos-infect#1]
I think that if you mkdir /nixosroot and run the install on that and then reboot with root bind-mounted to /nixosroot, everything will work smoothly.

**Comment by elitak** [comment]
I use `rsync -a --delete` because it removes the clutter, uses the standard fs hierarchy, and does it within a single invocation. It's not efficient, but adds maybe 30s to the process. I'm prioritizing simplicity here.

If you want to preserve the existing FS and just install once without copying, then yes, that would be a way to do it, but it would also require nixos-install to not be broken, as it currently is, by https://github.com/NixOS/nixpkgs/issues/10230

My default use case is to fully replace the OS and throw away everything, since I only ever run this on freshly deployed images. If you have a different purpose, just fork this repo and change a few lines.

**Comment by elitak** [comment]
Using nixos-lustrate now, instead of bindmount / rsync hacks.
