### ISSUE TITLE
Works on Hetzner Cloud, but no ssh running?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [elitak/nixos-infect#25]
The script seems to work fine in the sense that it installs nixos, and reboot, and nixos starts fine.

I can't contact the server though, so the network is down, or possibly ssh is not running.

**Comment by alexanderkjeldaas** [comment]
<img width="902" alt="skarmavbild 2018-04-19 kl 22 31 26" src="https://user-images.githubusercontent.com/339369/39016672-6f163dca-4421-11e8-878d-beeab35af22e.PNG">
yes, networking issues during boot.

**Comment by elitak** [comment]
Run `ip a; ip r; ip -6 r` before and after running `nixos-infect', compare them against each other and what's in `/etc/nixos/networking.nix`. Probably it failed to extract the network configuration and put it into `networking.nix`.

**Comment by danbst** [comment]
I pretty much believe https://github.com/elitak/nixos-infect/pull/27 fixes this.

**Comment by asymmetric** [comment]
@alexanderkjeldaas can you confirm?

**Comment by danbst** [comment]
@asymmetric @alexanderkjeldaas @elitak I can confirm that workaround I've mentioned didn't help.

Though I've diagnosed root cause: `route` config is missing. In `networking.nix` I had to put
```
networking.interfaces.eth0.ipv4.routes = [ { address = "172.31.1.1"; prefixLength = 32; } ];
```
Then restart:
```
systemctl restart network-addresses-eth0
systemctl restart network-setup
```
Then `ip route` gets populated. Without route config `ip route` is empty and `ip route replace default ...` in networking setup script failes (no default route, nothing to replace).
