### ISSUE TITLE
why use this over nixos-in-place?

### ISSUE THREAD

**Issue by nhooyr** [elitak/nixos-infect#6]
What advantages/disadvantages does this script have over nixos-in-place?
Why was it created?

**Comment by nhooyr** [comment]
I see the comment on the script but I think it should be in the `README.md` as well.

**Comment by elitak** [comment]
nixos-in-place is overly complex and boots NixOS from a pseudo-root instead of the natural root `/`. This script, by contrast, replaces the entire OS, leaving nothing behind, except `/old-root` which can be `rm -r`'ed next boot.

Additionally, nixos-in-place tries to support many different platforms, whereas this script only supports Digital Ocean, and as a consequence, is much simpler. Being arguably easier to understand, it should lend itself better toward customization or repurposing for different providers.

I forewent a README.md in a conscious effort to keep the whole thing as minimalistic as possible.

**Comment by nhooyr** [comment]
Thanks!
